//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.03 at 05:40:28 PM BRT 
//


package br.com.documentonorma;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.documentonorma package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.documentonorma
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocumentDetail }
     * 
     */
    public DocumentDetail createDocumentDetail() {
        return new DocumentDetail();
    }

    /**
     * Create an instance of {@link InsertDocumentRequest }
     * 
     */
    public InsertDocumentRequest createInsertDocumentRequest() {
        return new InsertDocumentRequest();
    }

    /**
     * Create an instance of {@link DeleteDocumentRequest }
     * 
     */
    public DeleteDocumentRequest createDeleteDocumentRequest() {
        return new DeleteDocumentRequest();
    }

    /**
     * Create an instance of {@link GetDocumentDetailRequest }
     * 
     */
    public GetDocumentDetailRequest createGetDocumentDetailRequest() {
        return new GetDocumentDetailRequest();
    }

    /**
     * Create an instance of {@link GetDocumentDetailResponse }
     * 
     */
    public GetDocumentDetailResponse createGetDocumentDetailResponse() {
        return new GetDocumentDetailResponse();
    }

    /**
     * Create an instance of {@link DeleteDocumentResponse }
     * 
     */
    public DeleteDocumentResponse createDeleteDocumentResponse() {
        return new DeleteDocumentResponse();
    }

}
